# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "lambda-redis-mongo"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "lambda-sfn"
s3_prefix = "lambda-sfn"
region = "eu-central-1"
parameter_overrides = "DbUriParameterName=\"/drone-tracking-app/db-uri\" RedisHostName=\"clustercfg.redis.ri1ocn.euc1.cache.amazonaws.com\" FlightRowDataTableName=\"row_flight_data\" LastPacketTimestampTableName=\"last_packet_timestamp\" RowFlightDataStreamArn=\"arn:aws:dynamodb:eu-central-1:585008087954:table/row_flight_data/stream/2025-02-22T14:40:47.896\" LastPacketTimestampStreamArn=\"arn:aws:dynamodb:eu-central-1:585008087954:table/last_packet_timestamp/stream/2025-03-08T18:51:56.232\" StepFunctionArn=\"arn:aws:states:eu-central-1:585008087954:stateMachine:TimeOutDetection\""
image_repositories = []
disable_rollback = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
